#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "Tinas VoIP (T-VoIP) ... yes i know very creative\n"
echo -e "type \"!help\" for a list of commands, !connect to connect"
while :
do
	read -r -e MAIN

	if [[ $MAIN == "!connect" ]];
	then
		if [[ -z "$HOST" ]];
		then
			echo -e "the \$HOST variable is empty"
		else
			echo -e "exchanging certificates"
			socat -u tcp:$HOST:$PORT OPEN:$DIRMAIN/.ssl/server.crt,creat
			socat -u FILE:$DIRMAIN/.ssl/client.crt tcp:$HOST:$PORT
			echo -e "connecting to $HOST:$PORT"
			arecord -f U8 -r 44100 -t wav - | socat STDIO openssl-connect:$HOST:$PORT,cert=$DIRMAIN/.ssl/client.pem,cafile=$DIRMAIN/.ssl/server.crt | aplay &
		fi
	elif [[ $MAIN == "!disconnect" ]];
	then
		killall "socat" > /dev/null 2>&1
	elif [[ $MAIN == "!gen" ]];
	then
		mkdir -p $DIRMAIN/.ssl
		openssl genrsa -out $DIRMAIN/.ssl/client.key 2048
		openssl req -new -key $DIRMAIN/.ssl/client.key -x509 -days 3653 -out $DIRMAIN/.ssl/client.crt
		cat $DIRMAIN/.ssl/client.key $DIRMAIN/.ssl/client.crt >$DIRMAIN/.ssl/client.pem
		echo -e "generated key, certificate and PEM file"
	elif [[ $MAIN == "!help" ]];
	then
		echo -e "list of commands:"
		echo -e "!help [this message]"
		echo -e "!gen [generates SSL key, certificate and PEM file]"
		echo -e "!connect [connects to the desired host]"
		echo -e "!disconnect [disconnects from the host]"
		echo -e "!exit [exit the script]"
	elif [[ $MAIN == "!exit" ]];
	then
		killall "socat" > /dev/null 2>&1
		break
	else
		echo -e "[${RED}ERROR${NC}] unknown command \"$MAIN\""
	fi
done
