#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "Tinas VoIP Server (T-VoIP S) ... yes i know very creative\n"
echo -e "type \"!help\" for a list of commands, !start to start"
while :
do
	read -r -e MAIN

	if [[ $MAIN == "!start" ]];
	then
		echo -e "waiting for client, to exchange certificates"
		socat -u FILE:$DIRMAIN/.ssl/server.crt tcp-listen:$PORT,reuseaddr
		socat -u tcp-listen:$PORT,reuseaddr OPEN:$DIRMAIN/.ssl/client.crt,creat
		echo -e "listening on port $PORT for audio data"
		arecord -f cd -t wav - | socat openssl-listen:$PORT,reuseaddr,cert=$DIRMAIN/.ssl/server.pem,cafile=$DIRMAIN/.ssl/client.crt - | aplay &
	elif [[ $MAIN == "!stop" ]];
	then
		killall "socat" > /dev/null 2>&1
	elif [[ $MAIN == "!gen" ]];
	then
		mkdir -p $DIRMAIN/.ssl
		openssl genrsa -out $DIRMAIN/.ssl/server.key 2048
		echo -e "you will be asked to enter a \"common name\", please ensure that it matches your host name (the "ip" the client connects to)\n"
		openssl req -new -key $DIRMAIN/.ssl/server.key -x509 -days 3653 -out $DIRMAIN/.ssl/server.crt
		cat $DIRMAIN/.ssl/server.key $DIRMAIN/.ssl/server.crt >$DIRMAIN/.ssl/server.pem
		echo -e "generated key, certificate and PEM file"
	elif [[ $MAIN == "!help" ]];
	then
		echo -e "list of commands:"
		echo -e "!help [this message]"
		echo -e "!gen [generates SSL key, certificate and PEM file]"
		echo -e "!start [starts the server]"
		echo -e "!stop [stops the server]"
		echo -e "!exit [exit the script]"
	elif [[ $MAIN == "!exit" ]];
	then
		killall "socat" > /dev/null 2>&1
		break
	else
		echo -e "[${RED}ERROR${NC}] unknown command \"$MAIN\""
	fi
done
